volumes:
  mysql_data: {}

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_service
    volumes:
      - mysql_data:/var/lib/mysql
      
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306

  django:
    build:
      context: .
      dockerfile: lifangdjango/Dockerfile
    working_dir: /srv/lifang/
    volumes:
      - ./:/srv/lifang/
    #command: ["./manage.py", "runserver", "0:8000"]
    command: 
    command: ["python", "lifangdjango/manage.py", "runserver", "--settings=lifang_django.settings.local", "0.0.0.0:8000"]
    
    # environment:
    #   - DJANGO_DB_HOST=db
    depends_on:
      - mysql
    restart: always
    ports:
      - 8000:8000